import project1 from "../assets/projects/project-1.jpg";
import project2 from "../assets/projects/project-2.jpg";
import project3 from "../assets/projects/project-3.jpg";
import project4 from "../assets/projects/project-4.jpg";

export const HERO_CONTENT = `I am a passionate full stack developer with a knack for crafting robust and scalable web applications. With 5 years of hands-on experience, I have honed my skills in front-end technologies like React and Next.js, as well as back-end technologies like Node.js, MySQL, PostgreSQL, and MongoDB. My goal is to leverage my expertise to create innovative solutions that drive business growth and deliver exceptional user experiences.`;

export const ABOUT_TEXT = `I am a dedicated and versatile full stack developer with a passion for creating efficient and user-friendly web applications. With 5 years of professional experience, I have worked with a variety of technologies, including React, Next.js, Node.js, MySQL, PostgreSQL, and MongoDB. My journey in web development began with a deep curiosity for how things work, and it has evolved into a career where I continuously strive to learn and adapt to new challenges. I thrive in collaborative environments and enjoy solving complex problems to deliver high-quality solutions. Outside of coding, I enjoy staying active, exploring new technologies, and contributing to open-source projects.`;

export const EXPERIENCES = [
  
  {
    year: "2024 - Present",
    role: "AI Training Associate",
    company: "Outlier",
    description: `Responsible for reviewing and analyzing prompts and responses generated by AI language models to ensure relevance and accuracy.`,
    technologies: ["Javascript", "C++", "PHP", "Python"],
  },
];

export const PROJECTS = [
  {
    title: "Dental Clinic Website",
    image: project1,
    description:
      "Designed and developed a responsive and user-friendly website for a dental clinic, providing a seamless experience for patients to learn about services, book appointments, and view clinic informationn.",
    technologies: ["HTML", "CSS", "React", "Node.js", "MongoDB"],
  },
  {
    title: "Snake Game",
    image: project2,
    description:
      "An application for managing tasks and projects, with features such as task creation, assignment, and progress tracking.",
    technologies: ["HTML", "CSS", "Angular", "Firebase"],
  },
  {
    title: "Portfolio Website",
    image: project3,
    description:
      "Developed a classic Snake game using JavaScript, incorporating real-time user interactions and smooth gameplay.",
    technologies: ["HTML", "CSS", "Javascript"],
  },
  
];

export const CONTACT = {
  // address: "767 Fifth Avenue, New York, NY 10153 ",
  phoneNo: "+91 7876215235 ",
  email: "harishgarg.tech@gmail.com",
};
