import project1 from "../assets/projects/project-1.jpg";
import project2 from "../assets/projects/project-2.jpg";
import project3 from "../assets/projects/project-3.jpg";
import project4 from "../assets/projects/project-4.jpg";

export const HERO_CONTENT = `I am a dedicated full stack developer with 3 years of experience creating robust, scalable web applications. My expertise spans front-end frameworks like React and Next.js, combined with back-end technologies like Node.js, MySQL, and MongoDB. I am passionate about leveraging these skills to deliver innovative solutions that drive business growth and provide seamless, impactful user experiences.`;

export const ABOUT_TEXT = `I am a dedicated and versatile full stack developer with 5 years of experience in building efficient, user-focused web applications. My technical background includes working with React, Next.js, Node.js, MySQL, PostgreSQL, and MongoDB. My journey began with a strong curiosity about how things work, evolving into a career where I’m driven to learn and tackle new challenges. I excel in collaborative environments and enjoy solving complex problems to deliver impactful solutions. Beyond coding, I stay active, explore emerging technologies, and contribute to open-source projects.`;

export const EXPERIENCES = [
  
  {
    year: "2024 - Present",
    role: "AI Training Associate",
    company: "Outlier",
    description: `Responsible for reviewing and analyzing prompts and responses generated by AI language models to ensure relevance and accuracy.`,
    technologies: ["Javascript", "C++", "PHP", "Python"],
  },
];

export const PROJECTS = [
  {
    title: "Dental Clinic Website",
    image: project1,
    description:
      "Designed and developed a responsive and user-friendly website for a dental clinic, providing a seamless experience for patients to learn about services, book appointments, and view clinic informationn.",
    technologies: ["HTML", "CSS", "React", "Node.js", "MongoDB"],
  },
  {
    title: "Snake Game",
    image: project2,
    description:
      "An application for managing tasks and projects, with features such as task creation, assignment, and progress tracking.",
    technologies: ["HTML", "CSS", "Angular", "Firebase"],
  },
  {
    title: "Portfolio Website",
    image: project3,
    description:
      "Developed a classic Snake game using JavaScript, incorporating real-time user interactions and smooth gameplay.",
    technologies: ["HTML", "CSS", "Javascript"],
  },
  
];

export const CONTACT = {
  // address: "767 Fifth Avenue, New York, NY 10153 ",
  phoneNo: "+91 7876215235 ",
  email: "harishgarg.tech@gmail.com",
};
